export const WsCode = {
    LOGIN_TOADMIN:"LOGIN_TOADMIN.php",
    LIST_USER: "LIST_USER.php",
    LIST_STORY: "story/LIST_STORY.php",
    LIST_ICONS: "LIST_ICONS.php",
    LIST_STICKER: "LIST_STICKER.php",
    LIST_TYPE_ICON: "LIST_TYPE_ICON.php",
    UPDATE_USER: "UPDATE_ACCOUNT.php",
    UPDATE_STORY: "UPDATE_STORYS.php"
}